spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
server:
  servlet:
    context-path: /routeforms
